<?php

/**
 * OneOfInterface
 *
 * PHP version 8.1
 *
 * @package  eBay\Commerce\Notification\Model
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Notification API
 *
 * The eBay Notification API provides a comprehensive set of resources for developers to manage the entire lifecycle of asynchronous notifications from eBay. Users can browse available notification topics, configure and manage destination endpoints for receiving notifications, create and manage subscriptions to specific topics with optional filtering, and validate the integrity of received message payloads using public keys. The API supports both application-based and user-based subscriptions, utilizing OAuth 2.0 grant flows, and is essential for applications requiring timely updates on events such as order confirmations, listing revisions, feedback received, and user account changes.
 *
 * The version of the OpenAPI document: v1.6.7
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace eBay\Commerce\Notification\Model;

/**
 * Interface implemented by models generated from a `oneOf` schema.
 *
 * A `oneOf` schema is not represented by a value object; instead a value is one of the
 * composed member types. Classes implementing this interface only carry the metadata that
 * {@see ObjectSerializer::deserialize()} needs to resolve the concrete member type.
 *
 * @package eBay\Commerce\Notification\Model
 * @author  OpenAPI Generator team
 */
interface OneOfInterface
{
    /**
     * List of the types a value of this `oneOf` schema may be. Each entry uses the same
     * notation as the values of {@see ModelInterface::openAPITypes()}.
     *
     * @return string[]
     */
    public static function getOneOfTypes(): array;

    /**
     * Name of the discriminator property used to resolve the concrete member type, or null
     * when the schema has no discriminator.
     *
     * @return string|null
     */
    public static function getOneOfDiscriminator(): ?string;

    /**
     * Mapping of discriminator values to the concrete member type. Empty when the schema has
     * no discriminator.
     *
     * @return array<string,string>
     */
    public static function getOneOfDiscriminatorMappings(): array;
}
